export const countries = [
  { value: "PT", label: "Portugal" },
  { value: "AO", label: "Angola" },
  { value: "MZ", label: "Moçambique" },
  { value: "BR", label: "Brasil" },
  { value: "CV", label: "Cabo Verde" },
  { value: "GW", label: "Guiné-Bissau" },
  { value: "ST", label: "São Tomé e Príncipe" },
  { value: "TL", label: "Timor-Leste" },
  { value: "ES", label: "Espanha" },
  { value: "FR", label: "França" },
  { value: "DE", label: "Alemanha" },
  { value: "IT", label: "Itália" },
  { value: "GB", label: "Reino Unido" },
  { value: "US", label: "Estados Unidos" },
  { value: "NL", label: "Países Baixos" },
  { value: "BE", label: "Bélgica" },
  { value: "CH", label: "Suíça" },
  { value: "AT", label: "Áustria" },
  { value: "IE", label: "Irlanda" },
  { value: "LU", label: "Luxemburgo" },
  { value: "PL", label: "Polónia" },
  { value: "CZ", label: "República Checa" },
  { value: "DK", label: "Dinamarca" },
  { value: "SE", label: "Suécia" },
  { value: "NO", label: "Noruega" },
  { value: "FI", label: "Finlândia" },
  { value: "GR", label: "Grécia" },
  { value: "RO", label: "Roménia" },
  { value: "BG", label: "Bulgária" },
  { value: "HR", label: "Croácia" },
  { value: "HU", label: "Hungria" },
  { value: "SK", label: "Eslováquia" },
  { value: "SI", label: "Eslovénia" },
  { value: "EE", label: "Estónia" },
  { value: "LV", label: "Letónia" },
  { value: "LT", label: "Lituânia" },
  { value: "MT", label: "Malta" },
  { value: "CY", label: "Chipre" },
  { value: "JP", label: "Japão" },
  { value: "CN", label: "China" },
  { value: "IN", label: "Índia" },
  { value: "AU", label: "Austrália" },
  { value: "CA", label: "Canadá" },
  { value: "ZA", label: "África do Sul" },
  { value: "AE", label: "Emirados Árabes Unidos" },
  { value: "SA", label: "Arábia Saudita" },
  { value: "MX", label: "México" },
  { value: "AR", label: "Argentina" },
  { value: "CL", label: "Chile" },
  { value: "CO", label: "Colômbia" },
  { value: "OTHER", label: "Outro" },
];
